version: "3.9"
services:
    web:
        platform: "linux/amd64"
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NEXT_PUBLIC_CLIENTVAR: "clientvar"
        working_dir: /app
        ports:
            - "3000:3000"
        image: ${REPOSITORY_HOST}/${ORG_ID}/${MODULE_ID}:${PROJECT_VERSION}-${BUILD_NUMBER}
        environment:
            - DATABASE_URL="localhost:5432"
