##### Build Docker image from Vite project outputs

FROM arm64v8/node:19-alpine3.16
WORKDIR /web

ENV NODE_ENV production
ENV PORT 3000

RUN addgroup --system --gid 1001 etelie
RUN adduser --system --uid 1001 web

COPY --chown=etelie:web ../../dist ./dist

USER web:etelie
EXPOSE ${PORT}

CMD ["node", "server.js"]
