##### DEPENDENCIES

FROM arm64v8/node:19-alpine3.16 AS deps

# RUN apk add --no-cache libc6-compat openssl1.1-compat

WORKDIR /app

# Install Prisma Client
COPY ../../../prisma ./

# Install dependencies based on the preferred package manager
COPY ../../../package.json       ./
COPY ../../../package-lock.json* ./
RUN if [ -f package-lock.json ]; then npm ci; \
    else echo "Lockfile not found." && exit 1; \
    fi

##### BUILDER

FROM arm64v8/node:19-alpine3.16 AS builder
ARG DATABASE_URL
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN \
    if [ -f package-lock.json ]; then npm run build; \
    else echo "Lockfile not found." && exit 1; \
    fi

##### RUNNER

FROM arm64v8/node:19-alpine3.16 AS runner
WORKDIR /app

ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/next.config.mjs    ./
COPY --from=builder /app/public             ./public
COPY --from=builder /app/package.json       ./package.json

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static     ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT 3000

CMD ["node", "server.js"]
